.github/workflows/latest-changes.yml

✨ Add latest-changes GitHub Action

✨ Add latest-changes GitHub Action

---

README.md

⚗ First test from Camila's account

⚗ First test from Camila's account

---

README.md

⚗ Second experiment from Camila's account

⚗ Second experiment from Camila's account

---

README.md

⚗ Third experiment from Camila's account

⚗ Third experiment from Camila's account

---

README.md

⚗ Add another experiment

---

README.md

⚗ Something completely different

⚗ Something completely different

---

README.md

🐳 Where could my fishy be

---

README.md

🍻 Hey t'mate!

---

README.md

✨ Templates woohoo

---

README.md

🔊 Show the logs

---

README.md

🍻 Add random sad comment

---

.github/workflows/latest-changes.yml

🍻 Good bye t'mate

---

README.md

📝 Add note, time latest-changes

📝 Add note, time latest-changes

---

README.md

⚡️ Time Docker image speed

---

README.md

📝 Add message

---

README.md

🍻 Add a message about the pro-ness of using Docker tags

🍻 Add a message about the pro-ness of using Docker tags

---

.github/workflows/latest-changes.yml

⚗ Debug tmate authorized keys

---

README.md

📝 Add debugging message

---

README.md

🔊 Debug and debug, life is debugging

🔊 Debug and debug, life is debugging

---

README.md

⚗ More experiments

---

README.md

⚗ Moaaaare experiments

---

README.md

🍻 Dev, debug, dev, debug

---

README.md

👌 Awaiting for wife approval. Literally.

👌 Awaiting for wife approval. Literally.

---

README.md

📝 Cleanup README, remove debris 🚮

📝 Cleanup README, remove debris 🚮

---

README.md

⚗ Experiment, test label-approved

⚗ Experiment, test label-approved

---

.github/workflows/test.yml
README.md

📝 Update README

---

README.md

📝 New change

---

README.md

🔥 Remove stuff

---

app/main.py

✨ Add bad code to debug blacken

✨ Add bad code to debug blacken

---

drunken.py

🍻 Add more drunken code to check blacken action

🍻 Add more drunken code to check blacken action

---

.github/workflows/fake-test.yml
.github/workflows/smokeshow.yml
.github/workflows/test.yml
app/utils.py
tests/test_something.py
tests/test_utils.py

✨ Add Smokeshow

---

.github/workflows/build-docs.yml

👷 Only build docs on docs PRs

---

docs_src/body/tutorial001.py

📝 Tweak docs src

---

.github/workflows/build-docs.yml
.github/workflows/preview-docs.yml
.gitignore
requirements-docs.txt
scripts/docs.py

✨ Generate lang matrix for GitHub Actions

✨ Generate lang matrix for GitHub Actions

---

docs/en/docs/index.md

📝 Modify docs in PR

---

docs/en/docs/index.md

📝 Update docs

---

.github/workflows/build-docs.yml
.github/workflows/deploy-docs.yml

👷 Update docs CI with Cloudflare

👷 Update docs CI with Cloudflare

---

docs/en/docs/index.md

📝 Update docs again

---

docs/en/docs/index.md

📝 Update docs after main

---

docs/en/docs/index.md

📝 Update docs again and again

---

README.md

📝 Update README, try current latest-changes

📝 Update README, try current latest-changes

---

README.md

👷 Tweak latest-changes config

---

README.md

📝 Try latest-changes 3

---

README.md

📝 Update README, try latest-changes

📝 Update README, try latest-changes

---

README.md

📝 Try latest-changes 5

---

README.md
docs/en/docs/release-notes.md

✨ Update latest-changes

---

README.md

✨ Add a PR with a label

---

README.md
docs/en/docs/release-notes.md

📝 2 labels! And one release

---

README.md
docs/en/docs/release-notes.md

🥚 Add a fake easter egg, try custom label

🥚 Add a fake easter egg, try custom label

---

README.md

📝 Run a Docker CI cycle

---

README.md

📝 Run CI with Docker slim

---

.github/workflows/build-docs.yml
.github/workflows/deploy-docs.yml

🔧 Update configs for download and upload artifact

🔧 Update configs for download and upload artifact

---

drunken.py

🔥 Remove drunken code

---

.github/workflows/test.yml

👷 Update `test.yml` GitHub Action `upload-artifact`

👷 Update `test.yml` GitHub Action `upload-artifact`
